### PR TITLE
money heist chrome extension

### PR DESCRIPTION
**Pull request by DaNnyKg07**

### CODE REVIEW

**Comment by DevAndromeda** [comment]
@DaNnyKg07 could you rename the `MoneyHeist-ChromeExtension` directory to `ChromeExtension/MoneyHeist`?

**Comment by DaNnyKg07** [comment]
ok

**Comment by abh80** [comment]
Nice idea kek

**Comment by DaNnyKg07** [comment]
done

**Review by abh80 — APPROVED** [review]

**Pull request merged**
