### PR TITLE
Add twitter tweet notifier

### PR DESCRIPTION
**Pull request by FC5570**
1) Adds twitter tweet notifier, which can be used to notify someone when a specified twitter account tweets something.

### CODE REVIEW

**Comment by rhydderchc** [comment]
Hey, as per the rules (check the readme.md) :
> Should not make single pull requests for multiple languages/topics.

So it's advised to have two prs, with two different languages.
Also, I don't think `lolcode` is a **proper** language, it is a *esoteric* language.

**Comment by FC5570** [comment]
> Hey, as per the rules (check the readme.md) :
> 
> > Should not make single pull requests for multiple languages/topics.
> 
> So it's advised to have two prs, with two different languages. Also, I don't think `lolcode` is a **proper** language, it is a _esoteric_ language.

Sorry about that.

The readme also says [any programming language is accepted](https://github.com/DevSnowflake/hacktoberfest-2021#what-should-i-do), so, will this still be a valid PR, or do you want me to make another PR and remove lolcode from it?

**Comment by DevAndromeda** [comment]
`lolcode` is not a formal language so better to remove `lolcode` part

**Comment by FC5570** [comment]
Alright

**Pull request merged**
