### PR TITLE
Revamped the style & added search functionality

### PR DESCRIPTION
**Pull request by Nemika-Haj**
• Changed JavaScript to TypeScript
• Changed the Style (used brand colors)
• Added search functionality
  - In case the "snippets" are folders, it will redirect to the github repo. Otherwise, it will display it on the site.

### CODE REVIEW

**Comment by Nemika-Haj** [comment]
Added the missing files:
- `README.md`
- `vercel.json`
- The `prettier` configs

**Comment by Nemika-Haj** [comment]
Next seems to be unable to find the code directory on the server-side. I am unable to fix it as I've tried a bunch of different methods. However, if someone manages to fetch the files either by using the Github API or filestream, it will be great.

Note that I did attempt to use the Github API, but the hard task is to prevent getting Ratelimited.

**Comment by DevAndromeda** [comment]
> Next seems to be unable to find the code directory on the server-side. I am unable to fix it as I've tried a bunch of different methods. However, if someone manages to fetch the files either by using the Github API or filestream, it will be great.
> 
> Note that I did attempt to use the Github API, but the hard task is to prevent getting Ratelimited.

This would be less problematic if we fetched data from client side

**Comment by Nemika-Haj** [comment]
AHA! I managed to fix the issue!
It works splendidly - you can check it out https://code-examples-puce.vercel.app/ - there are two small steps in order to make it work.
You must create a **[Personal Access Token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token)**, and then add the following .env variables to Vercel in order to work;
- `NAME` equal to your username (for instance, Nemika-Haj)
- `TOKEN` equal to the token
So it must look something like this;
```env
NAME=Nemika-Haj
TOKEN=YourPersonalAccessToken
```

**Comment by rhydderchc** [comment]
> AHA! I managed to fix the issue! It works splendidly - you can check it out https://code-examples-puce.vercel.app/ - there are two small steps in order to make it work. You must create a **[Personal Access Token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token)**, and then add the following .env variables to Vercel in order to work;
> 
> * `NAME` equal to your username (for instance, Nemika-Haj)
> * `TOKEN` equal to the token
>   So it must look something like this;
> 
> ```shell
> NAME=Nemika-Haj
> TOKEN=YourPersonalAccessToken
> ```

I don't reckon you need a token for public repositories, do you? You can fetch data un-authenticated.

**Comment by rhydderchc** [comment]
@DevAndromeda could you do this? ^

**Pull request merged**
