### PR TITLE
CPP Programs

### PR DESCRIPTION
**Pull request by amankumarmahavar**

### CODE REVIEW

**Comment by amankumarmahavar** [comment]
Use all program

**Review by ASACHIT — CHANGES_REQUESTED** [review]
Hey,Your code in `calculator.cpp` encountered a mistake, and you failed to add `climits `in the header, resulting in a flood of handled errors in the terminal.

**Review by ASACHIT — CHANGES_REQUESTED** [review]
`Grade_calculator.cpp `got an error , there is a Typing mistake at last line, `G` letter is cause

**Comment by amankumarmahavar** [comment]
i have already updated and solve error

**Review by amankumarmahavar — COMMENTED** [review]
I already change file

**Pull request closed without merging**
