### PR TITLE
added note app

### PR DESCRIPTION
**Pull request by Souvik-Nayak**
I added the note app under the Node.js section as mentioned eaerlier. The app is bootstraped using Reactjs, Nodejs and Tailwind CSS.

### CODE REVIEW

**Comment by abh80** [comment]
I have tested this app and is working .

**Comment by Souvik-Nayak** [comment]
Thanks

**Comment by abh80** [comment]
Actual sent the previous comment by mistake

**Comment by abh80** [comment]
I have tested this app and is not working as expected

Here are the errors you need to resolve before getting this merged

image
image

**Pull request closed without merging**
